### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ghost** [kensung-lab/hypo#2] opened 2020-01-05 21:17 UTC
Hello, 
I am encountering a segmentation fault core dumped. This only happens with one specific fasta I am trying to polish (the exact same command with another assembly worked like a charm). 
Here is the command 
`./hypo/build/bin/hypo -r @il_names.txt -d curated.fasta -b curated.PE.sorted.bam -c 304 -s 120m -B curated.PB.sorted.bam -t 48 -o assemblyONT40kb.haplotigs_purged.hypopolished.fa`

And this one is the one working well
`./hypo/build/bin/hypo -r @il_names.txt -d curated.fasta -b curated.PE.sorted.bam -c 288 -s 120m -B curated.PB.sorted.bam -t 40 -o assemblyONT40kb.haplotigs_purged.hypopolished.fa`

The only 2 differences are 
- the curated.fasta are actually 2 different assemblies (though highly similar)
- the coverage -c value

Any idea? Thank you

**Comment by Ritu-Kundu** [comment] 2020-01-06 01:43
Hi,

Thanks for using our tool. Would it be possible for you to make the files available to us?

**Comment by ghost** [comment] 2020-01-06 10:02
Hello,
I solved the problem by going from 48 to 40 threads. Anyway I can share the files, I guess you would need the fasta and the 2 bams?

**Comment by Ritu-Kundu** [comment] 2020-01-06 14:47
Weird that the number of threads may cause the problem. We would like to investigate to catch the bug.  You could send the links for downloading the files (or files themselves if not too large) at dcsritu@nus.edu.sg
Thanks.

**Comment by ghost** [comment] 2020-01-06 16:11
Okay,
It will take a little while to download all the data on my side but I will do it.

**Comment by ghost** [comment] 2020-01-07 18:13
Hello,
I am experiencing segfault with 48 threads with other programs, such as samtools sort, hence I suspect the problem is on our side (hardware fault?). 
Unless you say otherwise I think we can assume for now hypo is not the problem.

**Comment by Ritu-Kundu** [comment] 2020-01-08 01:41
If you think that the problem is not hypo-specific, we can close the issue. You can always send your files if that is not the case. Good luck with your experiments!

**Closed as completed by Ritu-Kundu** 2020-01-08 01:41 UTC

**Comment by ghost** [comment] 2020-01-08 12:40
thanks! 
and btw hypo is very impressive in its polishing abilities.
